//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProgramlamaProjesi.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aile Terapisi.
        /// </summary>
        public static string aileTerapisi {
            get {
                return ResourceManager.GetString("aileTerapisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilişsel Davranışçı Terapi.
        /// </summary>
        public static string bilisselTerapi {
            get {
                return ResourceManager.GetString("bilisselTerapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        public static string merhaba {
            get {
                return ResourceManager.GetString("merhaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmenlerimiz.
        /// </summary>
        public static string ogretmenlerimiz {
            get {
                return ResourceManager.GetString("ogretmenlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretmenlerimiz hakkında bilgiler edinebilirsiniz..
        /// </summary>
        public static string ogretmenlerimizAciklama {
            get {
                return ResourceManager.GetString("ogretmenlerimizAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum Aç.
        /// </summary>
        public static string oturumAc {
            get {
                return ResourceManager.GetString("oturumAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu Kapat.
        /// </summary>
        public static string oturumu_kapat {
            get {
                return ResourceManager.GetString("oturumu_kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyun Şiddeti.
        /// </summary>
        public static string oyunSiddeti {
            get {
                return ResourceManager.GetString("oyunSiddeti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programlar.
        /// </summary>
        public static string programlar {
            get {
                return ResourceManager.GetString("programlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terapi Programlarımız.
        /// </summary>
        public static string programlarimiz {
            get {
                return ResourceManager.GetString("programlarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil ve konuşma terapistleri olarak erken çocukluk döneminden erişkinliğe kadar uzanan geniş bir yelpazede
        ///iletişim, dil, konuşma, ses ve yutma terapisi alanında çalışmalar yürütüyoruz..
        /// </summary>
        public static string programlarimiz_Aciklama {
            get {
                return ResourceManager.GetString("programlarimiz_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travma Terapisi.
        /// </summary>
        public static string travmaTerapisi {
            get {
                return ResourceManager.GetString("travmaTerapisi", resourceCulture);
            }
        }
    }
}
