//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrnekYazi
    {
        public int OrnekYaziID { get; set; }
        public string OrnekYaziBaslik { get; set; }
        public string OrnekYaziAciklama { get; set; }
        public string OrnekYaziVideoLink { get; set; }
    }
}
