//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderID { get; set; }
        public byte[] SliderFoto { get; set; }
        public string SliderBaslik { get; set; }
        public string SliderAciklama { get; set; }
        public string SliderResimYolu { get; set; }
        public Nullable<System.DateTime> BaslangicTarih { get; set; }
        public Nullable<System.DateTime> BitisTarih { get; set; }
    }
}
