//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TanitimYazilari
    {
        public int TanitimID { get; set; }
        public string TanitimBaslik { get; set; }
        public string TanitimYazisi { get; set; }
        public string Renk { get; set; }
        public string ResimYolu { get; set; }
    }
}
